package com.lzy.entity;

import lombok.experimental.Accessors;

import java.io.Serializable;
import java.util.Date;

public class AppFiles implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.origin_name
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String originName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.file_name
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.folder_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Long folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.file_type
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.file_path
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.file_data
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String fileData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.user_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.is_bin
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String isBin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.is_deleted
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String isDeleted;

    private String isFinished;
    private String fileIdentifier;
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_files.create_time
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_files
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.id
     *
     * @return the value of app_files.id
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Long getFileSize(){return fileSize;}

    public void setFileSize(Long fileSize){this.fileSize = fileSize;}

    public String getFileIdentifier(){
        return fileIdentifier;
    }

    public void setFileIdentifier(String fileIdentifier){
        this.fileIdentifier = fileIdentifier;
    }

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.id
     *
     * @param id the value for app_files.id
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.origin_name
     *
     * @return the value of app_files.origin_name
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.origin_name
     *
     * @param originName the value for app_files.origin_name
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setOriginName(String originName) {
        this.originName = originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.file_name
     *
     * @return the value of app_files.file_name
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.file_name
     *
     * @param fileName the value for app_files.file_name
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.folder_id
     *
     * @return the value of app_files.folder_id
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Long getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.folder_id
     *
     * @param folderId the value for app_files.folder_id
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setFolderId(Long folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.file_type
     *
     * @return the value of app_files.file_type
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.file_type
     *
     * @param fileType the value for app_files.file_type
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.file_path
     *
     * @return the value of app_files.file_path
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.file_path
     *
     * @param filePath the value for app_files.file_path
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.file_data
     *
     * @return the value of app_files.file_data
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getFileData() {
        return fileData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.file_data
     *
     * @param fileData the value for app_files.file_data
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setFileData(String fileData) {
        this.fileData = fileData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.user_id
     *
     * @return the value of app_files.user_id
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.user_id
     *
     * @param userId the value for app_files.user_id
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.is_bin
     *
     * @return the value of app_files.is_bin
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getIsBin() {
        return isBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.is_bin
     *
     * @param isBin the value for app_files.is_bin
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setIsBin(String isBin) {
        this.isBin = isBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.is_deleted
     *
     * @return the value of app_files.is_deleted
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.is_deleted
     *
     * @param isDeleted the value for app_files.is_deleted
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    //add new
    public String getIsFinished() {
        return isFinished;
    }

    public void setIsFinished(String isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_files.create_time
     *
     * @return the value of app_files.create_time
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_files.create_time
     *
     * @param createTime the value for app_files.create_time
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_files
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", originName=").append(originName);
        sb.append(", fileName=").append(fileName);
        sb.append(", folderId=").append(folderId);
        sb.append(", fileType=").append(fileType);
        sb.append(", filePath=").append(filePath);
        sb.append(", fileData=").append(fileData);
        sb.append(", userId=").append(userId);
        sb.append(", isBin=").append(isBin);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", isFinished=").append(isFinished);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}