package com.lzy.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class AppFolder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.name
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.user_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.parent_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.folder_size
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String folderSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.is_bin
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String isBin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.is_deleted
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private String isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_folder.create_time
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private Date createTime;

    private List<AppFolder> children;

    public List<AppFolder> getChildren() {
        return children;
    }

    public void setChildren(List<AppFolder> children) {
        this.children = children;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.id
     *
     * @return the value of app_folder.id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.id
     *
     * @param id the value for app_folder.id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.name
     *
     * @return the value of app_folder.name
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.name
     *
     * @param name the value for app_folder.name
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.user_id
     *
     * @return the value of app_folder.user_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.user_id
     *
     * @param userId the value for app_folder.user_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.parent_id
     *
     * @return the value of app_folder.parent_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.parent_id
     *
     * @param parentId the value for app_folder.parent_id
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.folder_size
     *
     * @return the value of app_folder.folder_size
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getFolderSize() {
        return folderSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.folder_size
     *
     * @param folderSize the value for app_folder.folder_size
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setFolderSize(String folderSize) {
        this.folderSize = folderSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.is_bin
     *
     * @return the value of app_folder.is_bin
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getIsBin() {
        return isBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.is_bin
     *
     * @param isBin the value for app_folder.is_bin
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setIsBin(String isBin) {
        this.isBin = isBin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.is_deleted
     *
     * @return the value of app_folder.is_deleted
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.is_deleted
     *
     * @param isDeleted the value for app_folder.is_deleted
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_folder.create_time
     *
     * @return the value of app_folder.create_time
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_folder.create_time
     *
     * @param createTime the value for app_folder.create_time
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", userId=").append(userId);
        sb.append(", parentId=").append(parentId);
        sb.append(", folderSize=").append(folderSize);
        sb.append(", isBin=").append(isBin);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}