package com.lzy.entity;

import java.io.Serializable;
import java.util.Date;

public class AppShare implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.user_id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.file_id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private Long fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.name
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.count
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.code
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.type
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.share_time
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private Date shareTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.end_time
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_share.is_show
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private String isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_share
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.id
     *
     * @return the value of app_share.id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.id
     *
     * @param id the value for app_share.id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.user_id
     *
     * @return the value of app_share.user_id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.user_id
     *
     * @param userId the value for app_share.user_id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.file_id
     *
     * @return the value of app_share.file_id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public Long getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.file_id
     *
     * @param fileId the value for app_share.file_id
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.name
     *
     * @return the value of app_share.name
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.name
     *
     * @param name the value for app_share.name
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.count
     *
     * @return the value of app_share.count
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.count
     *
     * @param count the value for app_share.count
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.code
     *
     * @return the value of app_share.code
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.code
     *
     * @param code the value for app_share.code
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.type
     *
     * @return the value of app_share.type
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.type
     *
     * @param type the value for app_share.type
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.share_time
     *
     * @return the value of app_share.share_time
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public Date getShareTime() {
        return shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.share_time
     *
     * @param shareTime the value for app_share.share_time
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setShareTime(Date shareTime) {
        this.shareTime = shareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.end_time
     *
     * @return the value of app_share.end_time
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.end_time
     *
     * @param endTime the value for app_share.end_time
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_share.is_show
     *
     * @return the value of app_share.is_show
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_share.is_show
     *
     * @param isShow the value for app_share.is_show
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_share
     *
     * @mbg.generated Thu Jul 25 12:34:13 HKT 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", fileId=").append(fileId);
        sb.append(", name=").append(name);
        sb.append(", count=").append(count);
        sb.append(", code=").append(code);
        sb.append(", type=").append(type);
        sb.append(", shareTime=").append(shareTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", isShow=").append(isShow);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}