package com.lzy.entity;

import java.util.ArrayList;
import java.util.List;

public class SysUploadTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public SysUploadTaskExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUploadIdIsNull() {
            addCriterion("upload_id is null");
            return (Criteria) this;
        }

        public Criteria andUploadIdIsNotNull() {
            addCriterion("upload_id is not null");
            return (Criteria) this;
        }

        public Criteria andUploadIdEqualTo(String value) {
            addCriterion("upload_id =", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotEqualTo(String value) {
            addCriterion("upload_id <>", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdGreaterThan(String value) {
            addCriterion("upload_id >", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdGreaterThanOrEqualTo(String value) {
            addCriterion("upload_id >=", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLessThan(String value) {
            addCriterion("upload_id <", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLessThanOrEqualTo(String value) {
            addCriterion("upload_id <=", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdLike(String value) {
            addCriterion("upload_id like", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotLike(String value) {
            addCriterion("upload_id not like", value, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdIn(List<String> values) {
            addCriterion("upload_id in", values, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotIn(List<String> values) {
            addCriterion("upload_id not in", values, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdBetween(String value1, String value2) {
            addCriterion("upload_id between", value1, value2, "uploadId");
            return (Criteria) this;
        }

        public Criteria andUploadIdNotBetween(String value1, String value2) {
            addCriterion("upload_id not between", value1, value2, "uploadId");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierIsNull() {
            addCriterion("file_identifier is null");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierIsNotNull() {
            addCriterion("file_identifier is not null");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierEqualTo(String value) {
            addCriterion("file_identifier =", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierNotEqualTo(String value) {
            addCriterion("file_identifier <>", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierGreaterThan(String value) {
            addCriterion("file_identifier >", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("file_identifier >=", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierLessThan(String value) {
            addCriterion("file_identifier <", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierLessThanOrEqualTo(String value) {
            addCriterion("file_identifier <=", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierLike(String value) {
            addCriterion("file_identifier like", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierNotLike(String value) {
            addCriterion("file_identifier not like", value, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierIn(List<String> values) {
            addCriterion("file_identifier in", values, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierNotIn(List<String> values) {
            addCriterion("file_identifier not in", values, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierBetween(String value1, String value2) {
            addCriterion("file_identifier between", value1, value2, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileIdentifierNotBetween(String value1, String value2) {
            addCriterion("file_identifier not between", value1, value2, "fileIdentifier");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNull() {
            addCriterion("file_name is null");
            return (Criteria) this;
        }

        public Criteria andFileNameIsNotNull() {
            addCriterion("file_name is not null");
            return (Criteria) this;
        }

        public Criteria andFileNameEqualTo(String value) {
            addCriterion("file_name =", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotEqualTo(String value) {
            addCriterion("file_name <>", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThan(String value) {
            addCriterion("file_name >", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("file_name >=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThan(String value) {
            addCriterion("file_name <", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLessThanOrEqualTo(String value) {
            addCriterion("file_name <=", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameLike(String value) {
            addCriterion("file_name like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotLike(String value) {
            addCriterion("file_name not like", value, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameIn(List<String> values) {
            addCriterion("file_name in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotIn(List<String> values) {
            addCriterion("file_name not in", values, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameBetween(String value1, String value2) {
            addCriterion("file_name between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andFileNameNotBetween(String value1, String value2) {
            addCriterion("file_name not between", value1, value2, "fileName");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNull() {
            addCriterion("bucket_name is null");
            return (Criteria) this;
        }

        public Criteria andBucketNameIsNotNull() {
            addCriterion("bucket_name is not null");
            return (Criteria) this;
        }

        public Criteria andBucketNameEqualTo(String value) {
            addCriterion("bucket_name =", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotEqualTo(String value) {
            addCriterion("bucket_name <>", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThan(String value) {
            addCriterion("bucket_name >", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameGreaterThanOrEqualTo(String value) {
            addCriterion("bucket_name >=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThan(String value) {
            addCriterion("bucket_name <", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLessThanOrEqualTo(String value) {
            addCriterion("bucket_name <=", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameLike(String value) {
            addCriterion("bucket_name like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotLike(String value) {
            addCriterion("bucket_name not like", value, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameIn(List<String> values) {
            addCriterion("bucket_name in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotIn(List<String> values) {
            addCriterion("bucket_name not in", values, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameBetween(String value1, String value2) {
            addCriterion("bucket_name between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andBucketNameNotBetween(String value1, String value2) {
            addCriterion("bucket_name not between", value1, value2, "bucketName");
            return (Criteria) this;
        }

        public Criteria andObjectKeyIsNull() {
            addCriterion("object_key is null");
            return (Criteria) this;
        }

        public Criteria andObjectKeyIsNotNull() {
            addCriterion("object_key is not null");
            return (Criteria) this;
        }

        public Criteria andObjectKeyEqualTo(String value) {
            addCriterion("object_key =", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotEqualTo(String value) {
            addCriterion("object_key <>", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyGreaterThan(String value) {
            addCriterion("object_key >", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyGreaterThanOrEqualTo(String value) {
            addCriterion("object_key >=", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyLessThan(String value) {
            addCriterion("object_key <", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyLessThanOrEqualTo(String value) {
            addCriterion("object_key <=", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyLike(String value) {
            addCriterion("object_key like", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotLike(String value) {
            addCriterion("object_key not like", value, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyIn(List<String> values) {
            addCriterion("object_key in", values, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotIn(List<String> values) {
            addCriterion("object_key not in", values, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyBetween(String value1, String value2) {
            addCriterion("object_key between", value1, value2, "objectKey");
            return (Criteria) this;
        }

        public Criteria andObjectKeyNotBetween(String value1, String value2) {
            addCriterion("object_key not between", value1, value2, "objectKey");
            return (Criteria) this;
        }

        public Criteria andTotalSizeIsNull() {
            addCriterion("total_size is null");
            return (Criteria) this;
        }

        public Criteria andTotalSizeIsNotNull() {
            addCriterion("total_size is not null");
            return (Criteria) this;
        }

        public Criteria andTotalSizeEqualTo(Long value) {
            addCriterion("total_size =", value, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeNotEqualTo(Long value) {
            addCriterion("total_size <>", value, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeGreaterThan(Long value) {
            addCriterion("total_size >", value, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("total_size >=", value, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeLessThan(Long value) {
            addCriterion("total_size <", value, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeLessThanOrEqualTo(Long value) {
            addCriterion("total_size <=", value, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeIn(List<Long> values) {
            addCriterion("total_size in", values, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeNotIn(List<Long> values) {
            addCriterion("total_size not in", values, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeBetween(Long value1, Long value2) {
            addCriterion("total_size between", value1, value2, "totalSize");
            return (Criteria) this;
        }

        public Criteria andTotalSizeNotBetween(Long value1, Long value2) {
            addCriterion("total_size not between", value1, value2, "totalSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeIsNull() {
            addCriterion("chunk_size is null");
            return (Criteria) this;
        }

        public Criteria andChunkSizeIsNotNull() {
            addCriterion("chunk_size is not null");
            return (Criteria) this;
        }

        public Criteria andChunkSizeEqualTo(Long value) {
            addCriterion("chunk_size =", value, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeNotEqualTo(Long value) {
            addCriterion("chunk_size <>", value, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeGreaterThan(Long value) {
            addCriterion("chunk_size >", value, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeGreaterThanOrEqualTo(Long value) {
            addCriterion("chunk_size >=", value, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeLessThan(Long value) {
            addCriterion("chunk_size <", value, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeLessThanOrEqualTo(Long value) {
            addCriterion("chunk_size <=", value, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeIn(List<Long> values) {
            addCriterion("chunk_size in", values, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeNotIn(List<Long> values) {
            addCriterion("chunk_size not in", values, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeBetween(Long value1, Long value2) {
            addCriterion("chunk_size between", value1, value2, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkSizeNotBetween(Long value1, Long value2) {
            addCriterion("chunk_size not between", value1, value2, "chunkSize");
            return (Criteria) this;
        }

        public Criteria andChunkNumIsNull() {
            addCriterion("chunk_num is null");
            return (Criteria) this;
        }

        public Criteria andChunkNumIsNotNull() {
            addCriterion("chunk_num is not null");
            return (Criteria) this;
        }

        public Criteria andChunkNumEqualTo(Integer value) {
            addCriterion("chunk_num =", value, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumNotEqualTo(Integer value) {
            addCriterion("chunk_num <>", value, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumGreaterThan(Integer value) {
            addCriterion("chunk_num >", value, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("chunk_num >=", value, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumLessThan(Integer value) {
            addCriterion("chunk_num <", value, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumLessThanOrEqualTo(Integer value) {
            addCriterion("chunk_num <=", value, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumIn(List<Integer> values) {
            addCriterion("chunk_num in", values, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumNotIn(List<Integer> values) {
            addCriterion("chunk_num not in", values, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumBetween(Integer value1, Integer value2) {
            addCriterion("chunk_num between", value1, value2, "chunkNum");
            return (Criteria) this;
        }

        public Criteria andChunkNumNotBetween(Integer value1, Integer value2) {
            addCriterion("chunk_num not between", value1, value2, "chunkNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_upload_task
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 03 17:23:15 HKT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}