package com.lzy.dao;

import com.lzy.entity.AppFolder;
import com.lzy.entity.AppFolderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    long countByExample(AppFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int deleteByExample(AppFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int insert(AppFolder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int insertSelective(AppFolder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    List<AppFolder> selectByExample(AppFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    AppFolder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByExampleSelective(@Param("row") AppFolder row, @Param("example") AppFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByExample(@Param("row") AppFolder row, @Param("example") AppFolderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByPrimaryKeySelective(AppFolder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_folder
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByPrimaryKey(AppFolder row);

    int batchToBin(@Param("idList") List<Long> idList);
}