package com.lzy.dao;

import com.lzy.entity.AppUser;
import com.lzy.entity.AppUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    long countByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int deleteByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int insert(AppUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int insertSelective(AppUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    List<AppUser> selectByExample(AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    AppUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByExampleSelective(@Param("row") AppUser row, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByExample(@Param("row") AppUser row, @Param("example") AppUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByPrimaryKeySelective(AppUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_user
     *
     * @mbg.generated Thu Jul 18 12:45:29 HKT 2024
     */
    int updateByPrimaryKey(AppUser row);
}