package com.lzy.dao;

import com.lzy.entity.SysUploadTask;
import com.lzy.entity.SysUploadTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUploadTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    long countByExample(SysUploadTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int deleteByExample(SysUploadTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int insert(SysUploadTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int insertSelective(SysUploadTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    List<SysUploadTask> selectByExample(SysUploadTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    SysUploadTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int updateByExampleSelective(@Param("row") SysUploadTask row, @Param("example") SysUploadTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int updateByExample(@Param("row") SysUploadTask row, @Param("example") SysUploadTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int updateByPrimaryKeySelective(SysUploadTask row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_upload_task
     *
     * @mbg.generated Tue Sep 03 17:23:15 HKT 2024
     */
    int updateByPrimaryKey(SysUploadTask row);
}